# AUTOGENERATED FROM 'app/queries/meeting/create_meeting_async.edgeql' WITH:
#     $ gel-py


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

# import asyncio
import gel

#
# from app.utils.base62 import Base62
# from app.utils.geldb import gel_client


@dataclasses.dataclass
class CreateMeetingAsyncResult:
    id: uuid.UUID
    url_code: str


async def create_meeting_async(
    executor: gel.AsyncIOExecutor,
    *,
    url_code: str,
) -> CreateMeetingAsyncResult:
    return cast(
        CreateMeetingAsyncResult,
        await executor.query_single(
            """\
        with
            url_code := <str>$url_code
        select (
            insert Meeting {
                url_code := url_code,
            }
        ) {url_code}\
        """,
            url_code=url_code,
        ),
    )


#
# if __name__ == '__main__':
#     async def main() -> None:
#         await create_meeting_async(gel_client, url_code=Base62.encode(uuid.uuid4().int))
#
#     asyncio.run(main())
